#!/bin/bash

#--no-check-certificate

FAST_ERROR_RAIZO=0
FAST_ERROR_RAIZO_LOG=''
WEBSERVER_FQDN="www.securitylab.fr/liveraizo-update"

PossedeIP_fast_update()
{
	if ! /bin/ip add show scope global | awk '/^ +inet .+ scope global .*$/ {exit 1}'
	then # IPv4
		return 0
	elif ! /bin/ip -6 addr show scope global | awk '/^ +inet6 .+ scope global .*$/ {exit 1}'
	then # IPv6
		return 0
	fi
	return 1
}

Executer_fast_update()
{

#source /opt/securitylab/etc/fast-update.conf

local REP_SCRIPT_LOCAL='/tmp/'

local CERROR='\e[0;1;31m' # Rouge
local CINFO='\e[4;1;31m' # Rouge souligné
local CCOMMANDE='\e[1;37m' # Blanc
local CFILE='\e[1;33m' # Jaune
local COPTION='\e[1;34m' # Bleu
local COK='\e[1;32m' # Vert

local SansCouleur='\e[0;m'

if [ "$1" = '-h' ] || [ "$1" = '-H' ]
then
	echo '  => Download a file Name on a WebServer and processes it.'
	echo 'fast-update [-s WebServer] [Name]'
	echo "By default, WebServer is : ${WEBSERVER_FQDN}"
	echo "By default, Name is : ${NAME_REMOTE_SCRIPT_BY_DEFAULT}"
	return
fi

if [ "$1" = '-s' ] || [ "$1" = '-S' ]
then
	shift
	if (( $# < 1 ))
	then
		>&2 echo -e "${CERROR}Error : The number of parameter is uncorrect${SansCouleur}"
		FAST_ERROR_RAIZO=1
		FAST_ERROR_RAIZO_LOG='The number of parameter is uncorrect'
		return
	fi
	local WEBSERVER_FQDN="$1"
	shift
fi

local NOM_SCRIPT="${NAME_REMOTE_SCRIPT_BY_DEFAULT}"
if (( $# != 0 ))
then
	NOM_SCRIPT="$1"
	shift
fi

if ! PossedeIP_fast_update
then
	>&2 echo -e "${CERROR}Error : You must have an IP address${SansCouleur}"
	FAST_ERROR_RAIZO=2
	FAST_ERROR_RAIZO_LOG='You must have an IP address'
	return
fi


# Le nom du script est en minuscule sur le serveur web
if [ -n "${BASH}" ]
then
	# bash
	local NOM_SCRIPT_SUR_WEB=${NOM_SCRIPT,,}
else
	# zsh
	local NOM_SCRIPT_SUR_WEB=${NOM_SCRIPT:l}
fi

local NOM_SCRIPT_LOCAL
NOM_SCRIPT_LOCAL=$(mktemp 'fast-update.XXXXXXXXXX' --tmpdir="${REP_SCRIPT_LOCAL}")

echo -e "${CCOMMANDE}* ${NOM_SCRIPT} : Download of ${CFILE}https://${WEBSERVER_FQDN}/${NOM_SCRIPT_SUR_WEB}${CCOMMANDE} into ${CFILE}${NOM_SCRIPT_LOCAL}${SansCouleur}"
if ! wget --no-check-certificate -nv "https://${WEBSERVER_FQDN}/${NOM_SCRIPT_SUR_WEB}" -O "${NOM_SCRIPT_LOCAL}"
then
	>&2 echo -e "${CERROR}Error : An error occurred in the download of ${CINFO}${NOM_SCRIPT}${SansCouleur}"
	rm -f "${NOM_SCRIPT_LOCAL}"
	FAST_ERROR_RAIZO=2
	FAST_ERROR_RAIZO_LOG="An error occurred in the download of ${NOM_SCRIPT}"
	return
fi

echo -e "${CCOMMANDE}* ${NOM_SCRIPT} : Execution of ${CFILE}${NOM_SCRIPT_LOCAL} ${COPTION}$*${SansCouleur}"
source "${NOM_SCRIPT_LOCAL}" "$@"

rm -f "${NOM_SCRIPT_LOCAL}"

if (( FAST_ERROR_RAIZO != 0 ))
then
	>&2 echo -e "${CERROR}* Error : Failure !!! ${FAST_ERROR_RAIZO_LOG}${SansCouleur}"
else
	echo -e "${COK}* ${NOM_SCRIPT} : Finished update${SansCouleur}"
fi

}
Executer_fast_update "$@"
unset Executer_fast_update
unset PossedeIP_fast_update
