#!/bin/bash

USER=$1
USER=${USER:-debian}


if [ ! -d /home/${USER}/malware_samples ] ; then

	mkdir /home/${USER}/malware_samples
fi

wget https://github.com/securitylab-repository/scripts/raw/refs/heads/main/download/fichiers_cours_malwares.zip.xz -O /home/${USER}/malware_samples/fichiers_cours_malwares.zip.xz

xz -d /home/${USER}/malware_samples/fichiers_cours_malwares.zip.xz