#!/bin/bash

fast-update install_radare2
fast-update install_oledump
fast-update install_inetsim

sudo apt -y update
sudo apt -y install upx-ucl yara
sudo pip3 install yara-python

git clone https://github.com/ytisf/theZoo.git /home/debian/malware_samples/thezoo
